permalink: /posts/:title

name: Jon Morgan

description: Hi! I'm Jon Morgan, a Software Developer and Computer Science student at City, Universiy of London. I love programming small projects, hacking hardware and researching computing
